### ISSUE TITLE
Anki collection path

### ISSUE THREAD

**Issue by caseros** [jlitven/vocabulary_flash_cards_creator#4]
Hi,

Not sure what file I'm supposed to direct towards.

thanks.

**Comment by jlitven** [comment]
I don't understand your question.

**Comment by caseros** [comment]
"Upon running for the first time, vexer will ask you for your Anki collection path " 

Not sure what the 'collection path' is. 

/Anki/??

thanks!

**Comment by caseros** [comment]
dw, got it :) 
(previous issue, with same issue)

**Comment by jlitven** [comment]
Oh, it's the path to your .anki2 file. It should be something
like /Users/user_name/Documents/Anki/User 1/collection.anki2.

Cheers
